apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  hostname: busybox
  subdomain: my-subdomain
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    name: busybox
