apiVersion: v1
kind: Pod
metadata:
  name: lp-nginx-demo
  labels:
    app: nginx
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:      #this block performs readiness probes
#      httpGet:
#        path: /
#        port: 80
      tcpSocket:
         port: 800
      initialDelaySeconds: 5
      periodSeconds: 5
