apiVersion: v1
kind: Pod 
metadata:
  name: myapp 
  labels:
    app: myapp 
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - image: leaddevops/petclinic:3
      name: petclinic
      ports:
        - containerPort: 8080 
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 3
      livenessProbe:
        httpGet:
           path: /petclinic
           port: 8080
#        exec:
#          command: ["curl","localhost:8080","/petclinic"]
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 3
