apiVersion: v1
kind: Pod
metadata:
  name: rp-nginx-demo
  labels:
    app: nginx
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:      #this block performs readiness probes
      httpGet:
        path: /
        port: 80
#      tcpSocket:
#         port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
