apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: prod
spec:
  hard:
    pods: "4"
    replicationcontrollers: "2"
    services: "10"
    count/deployments.apps: "2"
    count/replicasets.apps: "2"
