apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: ZXhhbXBsZS11c2Vy
  password: ZXhhbXBsZS1wYXNzd29yZA==

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret                #Name of secret
            key: username             #secret key
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never
