apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
       - image: lerndevops/mongo
         name: mongo
         volumeMounts:
           - name: pv
             mountPath: "/data/db"
      volumes:
       - name: pv
         persistentVolumeClaim:
            claimName: myapp-pvc
