apiVersion: v1
kind: Pod
metadata:
  name: readonly-pod
spec:
  containers:
  - name: cont1
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: my-volume
      mountPath: /volume
      readOnly: false
  volumes:
  - name: my-volume
    emptyDir: {}
