FROM ubuntu AS builder         
ARG DEBIAN_FRONTEND=noninteractive   
# Install golang
RUN apt-get update && apt-get install -y golang-go   
# Copy source code
ADD https://github.com/lerndevops/code/raw/refs/heads/main/app.go .                                             
RUN CGO_ENABLED=0 go build app.go

FROM alpine
# Copy artifact from builder stage                   
COPY --from=builder /app .   
CMD ["./app"]
